books/urls.py
from django.conf.urls import url
from . import views

app_name = 'books'

urlpatterns = [
    url(r'^(?P<book_id>[0-9]+)/return/$', views.return_book, name='return'),
    url(r'^(?P<book_id>[0-9]+)/(?P<user_id>[0-9]+)/borrow/$', views.borrow, name='borrow'),
    url(r'^(?P<book_id>[0-9]+)/$', views.detail, name="detail"),
    url(r'^reviews/(?P<book_id>[0-9]+)/(?P<user_id>[0-9]+)/$', views.reviews, name='reviews'),
    url(r'^add_book/', views.add_book, name='add_book'),
    url(r'^search/', views.search, name='search'),
    url(r'^$', views.index, name='index'),
    url(r'^adminpage/', views.adminpage, name="adminpage"),
    url(r'^delete/(?P<book_id>[0-9]+)/$', views.delete_book, name='delete'),

    # todo: 'user' app for these?
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.profile, name="profile"),
    url(r'^register/', views.register, name="register"),
]

books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class Book(models.Model):
    ISBN = models.CharField(max_length=150)
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=500)
    author = models.CharField(max_length=150)
    publication_year = models.IntegerField(default=0)
    publisher = models.CharField(max_length=150)
    page_count = models.IntegerField(default=0)
    cover_URL = models.URLField(max_length=250)

    STATUS = (
        ('a', 'Available'),
        ('o', 'On loan'),
        ('n', 'Not for loan'),
    )

    status = models.CharField(
        max_length=1, choices=STATUS, blank=True, default='a')
    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    # temporarily
    borrowed = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Borrowing(models.Model):
    borrowing_date = models.DateTimeField(auto_now_add=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    returning_date = models.DateTimeField(null=True, blank=True)
    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)


class Review(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    review = models.CharField(max_length=1000)
    rating = models.IntegerField(default=1)
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE)
    reviewed_book = models.ForeignKey(Book, on_delete=models.CASCADE)

books/forms.py
from django import forms
from books.models import Book, Review
from django.contrib.auth.models import User

# book adding
class BookForm(forms.ModelForm):
    ISBN = forms.CharField(max_length=150)
    name = forms.CharField(max_length=150)
    description = forms.CharField(max_length=500)
    author = forms.CharField(max_length=150)
    publication_year = forms.IntegerField(min_value=1000, max_value=2999)
    publisher = forms.CharField(max_length=150)
    page_count = forms.IntegerField(min_value=0, max_value=9999)
    cover_URL = forms.URLField(max_length=200)

    class Meta:
        model = Book
        fields = ('ISBN', 'name', 'description', 'author', 'publication_year', 'publisher', 'page_count', 'cover_URL',)

# user registration
class UserForm(forms.ModelForm):
    username = forms.CharField(max_length=50)
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')

# review adding
class ReviewForm(forms.ModelForm):
    review = forms.CharField(max_length=1000)
    rating = forms.IntegerField(min_value=1, max_value=5)

    class Meta:
        model = Review
        fields = ('review', 'rating')

books/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from books.models import Book, Borrowing, Review
from books.forms import BookForm, UserForm, ReviewForm
from django.core.urlresolvers import reverse
from django.utils.formats import get_format
from datetime import datetime
from django.utils.dateformat import DateFormat
from django.contrib.auth.decorators import login_required, user_passes_test
from django.template import RequestContext, Context
from django.db.models import Q


def index(request):
    all_books = Book.objects.all()
    all_borrowings = Borrowing.objects.all()
    context = {'all_books': all_books, 'all_borrowings': all_borrowings}
    return render(request, 'books/index.html', context)

@user_passes_test(lambda u: u.is_superuser)
def add_book(request):
    booksurl = request.build_absolute_uri(reverse('books:index'))
    if request.method == 'POST':
        book_form = BookForm(request.POST)
        print (book_form.errors)
        if book_form.is_valid():
            book_ISBN = book_form.cleaned_data['ISBN']
            book_name = book_form.cleaned_data['name']
            book_description = book_form.cleaned_data['description']
            book_author = book_form.cleaned_data['author']
            book_publication_year = book_form.cleaned_data['publication_year']
            book_publisher = book_form.cleaned_data['publisher']
            book_page_count = book_form.cleaned_data['page_count']
            book_cover_URL = book_form.cleaned_data['cover_URL']
            new_book = Book(ISBN=book_ISBN, name=book_name, description=book_description, author=book_author,
                            publication_year=book_publication_year, publisher=book_publisher, page_count=book_page_count, cover_URL=book_cover_URL)
            new_book.save()
            return HttpResponseRedirect('/')
    else:
        book_form = BookForm()
    return render(request, 'books/add_book.html', {'booksurl': booksurl, 'book_form': book_form})

@user_passes_test(lambda u: u.is_superuser)
def adminpage(request):
    try:
        all_users = User.objects.all()
        all_borrowings = Borrowing.objects.all()
        all_reviews = Review.objects.all()
    except Book.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'admin_page.html', {'all_users': all_users, 'all_borrowings': all_borrowings, 'all_reviews': all_reviews})

# unique page for every book
def detail(request, book_id):
    try:
        book = Book.objects.get(pk=book_id)
        all_borrowings = Borrowing.objects.filter(book=book_id)
        all_reviews = Review.objects.filter(reviewed_book=book)
    except Book.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'books/detail.html', {'book': book, 'all_borrowings': all_borrowings, 'all_reviews': all_reviews})

# unique profile page for every user
@login_required
def profile(request, user_id):
    try:
        user = User.objects.get(pk=user_id)
        all_borrowings = Borrowing.objects.all()
        all_borrowings = Borrowing.objects.filter(borrower=user_id)
    except User.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'profile.html', {'user': user, 'all_borrowings': all_borrowings})

# search functionality
def search(request):
    query = request.GET.get('q')
    if query:
        results = Book.objects.filter(Q(name__icontains=query) | Q(author__icontains=query) | Q(publication_year__icontains=query) | Q(publisher__icontains=query) | Q(ISBN__icontains=query))
    else:
        results = Book.objects.all()
    all_borrowings = Borrowing.objects.all()
    context = {'results': results, 'q': query, 'all_borrowings': all_borrowings}
    return render(request, 'books/index.html', context)

@login_required
def borrow(request, book_id, user_id):
    detailurl = request.build_absolute_uri(
        reverse('books:detail', args=[book_id]))
    book = Book.objects.get(pk=book_id)
    user = User.objects.get(pk=user_id)
    book.borrowed = True
    book.borrower = user
    book.status = 'o'
    book.save()
    date = DateFormat(datetime.now()).format(get_format('DATE_FORMAT'))
    new_borrowing = Borrowing(borrowing_date=date, book=book, borrower=user)
    new_borrowing.save()
    # return render(request, 'books/detail.html', {'detailurl': detailurl, 'book': book})
    return HttpResponseRedirect('/')

@login_required
def return_book(request, book_id):
    detailurl = request.build_absolute_uri(
        reverse('books:detail', args=[book_id]))
    book = Book.objects.get(pk=book_id)
    book.borrowed = False
    book.borrower = None
    book.status = 'a'
    book.save()
    # return render(request, 'books/detail.html', {'detailurl': detailurl, 'book': book})
    return HttpResponseRedirect('/')

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print (user_form.errors)
    else:
        user_form = UserForm()
    return render(request, 'register.html', {'user_form': user_form, 'registered': registered})

# function to get every review for a specific book
def reviews(request, book_id, user_id):
    detailurl = request.build_absolute_uri(
        reverse('books:detail', args=[book_id]))
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        print (review_form.errors)
        if review_form.is_valid():
            date = DateFormat(datetime.now()).format(get_format('DATE_FORMAT'))
            review = review_form.cleaned_data['review']
            rating = review_form.cleaned_data['rating']
            book = Book.objects.get(pk=book_id)
            reviewer = request.user
            new_review = Review(
                date=date, review=review, rating=rating, reviewed_book=book, reviewer=reviewer)
            new_review.save()
            return HttpResponseRedirect(detailurl)
    else:
        review_form = ReviewForm()
    return render(request, 'books/review_book.html', {'detailurl': detailurl, 'review': review_form})

@user_passes_test(lambda u: u.is_superuser)
def delete_book(request, book_id):
    booksurl = request.build_absolute_uri(reverse('books:index'))
    detailurl = request.build_absolute_uri(reverse('books:detail', args=[book_id]))
    book = Book.objects.get(pk=book_id)
    # if OK is pressed, delete game and redirect to /games/
    if request.method == 'POST':
        book.delete()
        return HttpResponseRedirect('/')
    return render(request, 'books/delete.html', {'booksurl': booksurl, 'detailurl': detailurl, 'book': book})

templates/books/add_book.html
{% extends "base.html" %}
{% block content %}

<h3>Add book</h3>

<div class="container">

		<form class="form-signin" method="post" action="">
				{% csrf_token %}

				<label for="id_ISBN" class="sr-only">ISBN</label>
				<input class="form-control" name="ISBN" type="text" placeholder="ISBN" required /><br>

				<label for="id_book_name" class="sr-only">Book name</label>
				<input class="form-control" name="name" type="text" placeholder="Book name" required /><br>

				<label for="id_description" class="sr-only">Description</label>
				<textarea id="description-box" rows="4" class="form-control" name="description" type="text" placeholder="Description"></textarea><br>

				<label for="id_book_author" class="sr-only">Author</label>
				<input class="form-control" name="author" type="text" placeholder="Author" /><br>

				<label for="id_publication_year" class="sr-only">Publication year:</label>
				<input class="form-control" name="publication_year" type="number" min="1000" max="2999" step="1" placeholder="Publication year" required /><br>

				<label for="id_publisher" class="sr-only">Publisher</label>
				<input class="form-control" name="publisher" type="text" placeholder="Publisher" /><br>

				<label for="id_page_count" class="sr-only">Page count:</label>
				<input class="form-control" name="page_count" type="number" min="0" max="9999" step="1" placeholder="Page count" required /><br>

				<label for="id_cover_URL" class="sr-only">Cover URL</label>
				<input class="form-control" name="cover_URL" type="text" placeholder="Cover URL" /><br>

				<input class="btn btn-lg btn-primary btn-block" id="form-button" type="submit" value="Submit"/>

		</form>

</div>

{% endblock %}

templates/books/delete.html
{% extends "base.html" %}
{% block content %}

{% if user.is_authenticated and user.is_superuser %}

	<h3>You are about to delete {{ book.name }}</h3>

		<div class="container">
			<form action="" method="POST" width="40px" style="margin: auto;">
	        {% csrf_token %}
	            <button id="return" type="submit" class="btn btn-success btn" style="width: 80px;">OK</button>
	        </form>
	        <button id="borrow" type="cancel" style="width: 80px;" class="btn btn-danger btn">Cancel</button>
		</div>

	</div>

{% endif %}

	<script type="text/javascript">
	    document.getElementById("cancel").onclick = function () {
	        location.href = "{{ detailurl }}";
	    };
	</script>

{% endblock %}

templates/books/detail.html
{% extends "base.html" %} {% block content %}


<div class="container">

	<!-- the sidebar of book page -->
	<div class="row">
		<div class="col-sm-4 col-md-3">
			<div class="book-info">
				{% if user.is_authenticated %}
					{% if book.borrowed %}
						{% if book.borrower == user %}
							<a href="{% url 'books:return' book.id %}" class="btn btn-danger btn-sm" id="return" role="button">Return</a>
							<br>
							<br>
							<br>
						{% else %}
							Borrowed by
							<a href="{% url 'books:profile' book.borrower.id %}">
								<span class="username">{{ book.borrower }}</span>
							</a>
							<br>
							<br>
						{% endif %}
					{% else %}
						<a href="{% url 'books:borrow' book.id user.id %}" class="btn btn-default btn-sm" id="borrow" role="button">Borrow</a>
						<br>
						<br>
						<br>
					{% endif %}
				{% endif %}
				{% if book.cover_URL %}
				<img id="book-img" src="{{ book.cover_URL }}" class="img-responsive"> {% else %}
				<h3>No image to display</h3>
				{% endif %}
				<br>
				{% if user.is_superuser %}
					<a href="{% url 'books:delete' book.id %}" class="btn btn-danger btn-sm" id="return" role="button">Delete</a><br><br>
				{% endif %}
				<br>
				<br>
			</div>
		</div>

		<!-- basic information of the book -->
		<div class="col-sm-8 col-md-9">
			<h5>{{ book.author }}; {{ book.publication_year }}</h5>
			<h3 class="book-title">{{ book.name }}</h3>
			<h6>
				<strong>Publisher:</strong> {{ book.publisher }}
				<br>
				<strong>Page count:</strong> {{ book.page_count }}
				<br>
				<br>
			</h6>
			<p>{{ book.description }}</p>
		</div>
	</div>

	<!-- borrowing history section -->
	<div class="row">
		<div class="col-sm-4 col-md-3">
			<h3>Borrowing history</h3>
			<div class="latest">
				{% for borrowing in all_borrowings|dictsortreversed:"borrowing_date" %}
					{% if forloop.counter < 11 %}
						Borrowed by
						<a href="{% url 'books:profile' borrowing.borrower.id %}">
							<span class="username">{{ borrowing.borrower }}</span>
						</a>
						({{ borrowing.borrowing_date | date:"d.m." }})<br>
					{% endif %}
				{% endfor %}
			</div>
		</div>

		<!-- review section -->
		<div class="col-sm-8 col-md-9">
			<h3 class="h3_review">Reviews</h3>

			<!-- if user is authenticated -->
			{% if user.is_authenticated %}
			<div class="row">
				<a href="{% url 'books:reviews' book.id user.id %}" class="btn btn-success btn-sm" id="reviewbutton" role="button">Review this book</a>
			</div>

				<!-- if there is reviews -->
				{% if all_reviews %}
					{% for review in all_reviews %}
						{% if forloop.first %}
							<div class="row">
						{% endif %}

						<div class="col-xs-12 col-sm-6 col-lg-4" id="review">
							{{ review.rating }}/5
							<p>{{ review.review }}</p>
							<a href="{% url 'books:profile' review.reviewer.id %}">
								<p id="reviewer">
									<small>- {{ review.reviewer }}</small>
								</p>
							</a>
						</div>

						{% if forloop.counter|divisibleby:3 %}
							</div>
							<br>
							<div class="row">
						{% endif %}

						{% if forloop.last %}
							</div>
						{% endif %}

					{% endfor %}

				<!-- if there is no reviews -->
				{% else %}
					<p>There is no reviews</p>
				{% endif %}

			<!-- if user is not authenticated -->
			{% else %}

				<!-- if there is reviews -->
				{% if all_reviews %}
					{% for review in all_reviews %}
						{% if forloop.first %}
							<div class="row">
						{% endif %}

						<div class="col-xs-12 col-sm-6 col-lg-4" id="review">
							{{ review.rating }}/5
							<p>{{ review.review }}</p>
							<a href="{% url 'books:profile' review.reviewer.id %}">
								<p id="reviewer">
									<small>- {{ review.reviewer }}</small>
								</p>
							</a>
						</div>

						{% if forloop.counter|divisibleby:3 %}
							</div>
							<br>
							<div class="row">
						{% endif %}

						{% if forloop.last %}
							</div>
						{% endif %}

					{% endfor %}

				<!-- if there is no reviews -->
				{% else %}
					<p>There is no reviews</p>
				{% endif %}

			{% endif %}


		</div>
	</div>
</div>
</div>

{% endblock %}

templates/books/index.html
{% extends "base.html" %} {% block content %}

<!-- content -->

<article id="team">
    <div class="container">
        <div class="row">
            <div class="col-sm-9">
                <h3>ALL BOOKS</h3>

                <div id="search_container">
                    <form role="search" method="get" action="/search/">
                        <div class="input-group search-input-group">
                            <input type="text" class="form-control" id="searchBox" class="form-control" name="q" value="{{ query }}" placeholder="Search">
                            <span class="input-group-addon">
                                <button type="submit">
                                    <span class="glyphicon glyphicon-search" value="search"></span>
                                </button>
                            </span>
                        </div>
                    </form>
                </div>

                {% if all_books or results %}
                    <div class="table-responsive" id="all_books">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Borrow</th>
                                </tr>
                            </thead>
                            <tbody>

                                <!-- book results of the search functionality -->
                                {% if results %}

                                    {% for book in results %}
                                    <tr>
                                        <td>
                                            {{ book.author }}, {{ book.publication_year }}
                                            <a href="{% url 'books:detail' book.id %}">
                                                <h4>{{ book.name }}</h4>
                                            </a>
                                        </td>
                                        {% if book.status == 'o' %} {% if user.is_authenticated and book.borrower == user %}
                                        <td>
                                            <a href="{% url 'books:return' book.id %}?next={{request.path}}" class="btn btn-danger btn-sm" id="return" role="button">Return</a>
                                        </td>
                                        {% else %}
                                        <td>
                                            Borrowed by <a href="{% url 'books:profile' book.borrower.id %}"><span class="username">{{ book.borrower }}</span></a>
                                        </td>
                                        {% endif %} {% elif book.status == 'a' and user.is_authenticated %}
                                        <td>
                                            <a href="{% url 'books:borrow' book.id user.id %}?next={{request.path}}" class="btn btn-success btn-sm" id="borrow" role="button">Borrow</a>
                                        </td>
                                        {% else %}
                                        <td>Sign in!</td>
                                        {% endif %}
                                    </tr>
                                    {% endfor %}

                                <!-- listing of all books -->
                                {% elif all_books %}

                                    {% for book in all_books %}
                                        <tr>
                                            <td>
                                                {{ book.author }}, {{ book.publication_year }}
                                                <a href="{% url 'books:detail' book.id %}">
                                                    <h4>{{ book.name }}</h4>
                                                </a>
                                            </td>
                                            {% if book.status == 'o' %} {% if user.is_authenticated and book.borrower == user %}
                                            <td>
                                                <a href="{% url 'books:return' book.id %}?next={{request.path}}" class="btn btn-danger btn-sm" id="return" role="button">Return</a>
                                            </td>
                                            {% else %}
                                            <td>
                                                Borrowed by <a href="{% url 'books:profile' book.borrower.id %}"><span class="username">{{ book.borrower }}</span></a>
                                            </td>
                                            {% endif %} {% elif book.status == 'a' and user.is_authenticated %}
                                            <td>
                                                <a href="{% url 'books:borrow' book.id user.id %}?next={{request.path}}" class="btn btn-success btn-sm" id="borrow" role="button">Borrow</a>
                                            </td>
                                            {% else %}
                                            <td>Please sign in</td>
                                            {% endif %}
                                        </tr>
                                    {% endfor %}

                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                {% endif %}
            </div>

            <!-- sidebar of the landing page -->
            <div class="col-sm-3">
                <h3>LATEST BORROWINGS</h3>
                <div class="latest">
                    {% if all_borrowings %}
                        {% for borrowing in all_borrowings|dictsortreversed:"borrowing_date" %}
                            {% if forloop.counter < 11 %}
                                <tr>
                                    <td>
                                        {{ borrowing.book.name }} by
                                        <a href="{% url 'books:profile' borrowing.borrower.id %}">
                                            <span class="username">{{ borrowing.borrower }}</span>
                                        </a>
                                        ({{ borrowing.borrowing_date | date:"d.m." }})<br>
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</article>

<!-- content -->


{% endblock %}

templates/books/review_book.html
{% extends "base.html" %}
{% block content %}

<h3>Review book</h3>

	<div class="container">
		<form class="form-review" method="post" action="">
			{% csrf_token %}

			<label for="id_review" class="sr-only">Review</label>
			<textarea id="description-box" rows="6" class="form-control" name="review" type="text" placeholder="Review" required></textarea><br>

			<label for="id_rating" class="sr-only">Rating</label>
			<input class="form-control" name="rating" type="number" min="1" max="5" step="1" placeholder="Rating 1-5" required /><br>

			<input class="btn btn-sm btn-primary btn-block" id="form-button" type="submit" value="Submit"/>
			<a href="{{ detailurl }}" class="btn btn-success btn-sm" id="goback" role="button">Go back</a>
		</form>
	</div>

</div>

{% endblock %}