books/urls.py
from django.conf.urls import url
from . import views

app_name = 'books'

urlpatterns = [
    url(r'^(?P<book_id>[0-9]+)/return/$', views.return_book, name='return'),
    url(r'^(?P<book_id>[0-9]+)/(?P<user_id>[0-9]+)/borrow/$', views.borrow, name='borrow'),
    url(r'^(?P<book_id>[0-9]+)/$', views.detail, name="detail"),
    url(r'^reviews/(?P<book_id>[0-9]+)/(?P<user_id>[0-9]+)/$', views.reviews, name='reviews'),
    url(r'^add_book/', views.add_book, name='add_book'),
    url(r'^search/', views.search, name='search'),
    url(r'^$', views.index, name='index'),
    url(r'^adminpage/', views.adminpage, name="adminpage"),
    url(r'^delete/(?P<book_id>[0-9]+)/$', views.delete_book, name='delete'),

    # todo: 'user' app for these?
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.profile, name="profile"),
    url(r'^register/', views.register, name="register"),
]

templates/admin_page.html
{% extends "base.html" %}
{% block content %}

	<h3 class="profile-sidebar">Admin page</h3>

	<div class="container">
		<div class="row">

			<!-- listing of all users -->
			<div class="col-sm-6 col-md-6">
				<h3>All users</h3>
				<div class="table-responsive" id="all_books">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>Name</th>
								<th>Date joined</th>
							</tr>
						</thead>
						<tbody>
							{% if all_users %}
								{% for user in all_users|dictsortreversed:"date_joined" %}
									<tr>
										<td>
											<a href="{% url 'books:profile' user.id %}">
												<span class="username">{{ user.username }}</span>
											</a>
										</td>
										<td>
											{{ user.date_joined | date:"d.m.Y" }}
										</td>
									</tr>
								{% endfor %}
							{% endif %}
						</tbody>
					</table>
				</div>
			</div>

			<!-- listing of all borrowings -->
			<div class="col-sm-6 col-md-6">
				<h3>Borrowed books:</h3>

				{% if all_borrowings %}

				<div class="table-responsive" id="all_books">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>Name, author</th>
								<th>Borrower</th>
								<th>Borrowing date</th>
							</tr>
						</thead>
						<tbody>
							{% for borrowing in all_borrowings|dictsortreversed:"borrowing_date" %}
								<tr>
									<td>
										{{ borrowing.book.author }} –
										<a href="{% url 'books:detail' borrowing.book.id %}">
											<span class="username"><strong>{{ borrowing.book.name }}</strong></span>
										</a>
									</td>
									<td>
										{{ borrowing.borrower }}
									</td>
									<td>
										{{ borrowing.borrowing_date | date:"d.m.Y" }}
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
				{% endif %}
			</div>
		</div>
	</div>

{% endblock %}

templates/base.html
<!-- {% load staticfiles %} -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>InfoLib</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}">

</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a id="brand" href="/">InfoLib</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">

                <ul class="nav navbar-nav navbar-right">

                    {% if user.is_authenticated %}
                    <!-- navbar that an authenticated user sees -->

                        <li class="navbar-text">
                            <small>Signed in as
                                <a href="{% url 'books:profile' user.id %}">
                                    <span class="username">{{ user.username }}</span>
                                </a>
                            </small>
                        </li>

                        <!-- links that only admin sees -->
                        {% if user.is_superuser %}
                            <li>
                                <a href="{% url 'books:adminpage' %}">
                                    Admin page
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'books:add_book' %}">
                                    Add book
                                </a>
                            </li>
                        {% endif %}

                        <li>
                            <a href="{% url 'books:profile' user.id %}">
                                Profile
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'logout'%}">
                                Logout
                            </a>
                        </li>

                    {% else %}
                    <!-- navbar that a non-authenticated user sees -->

                        <li>
                            <a href="{% url 'login'%}?next={{request.path}}">
                                Login
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'books:register' %}">
                                Register
                            </a>
                        </li>

                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>
    <div class="sisalto">

        {% block content %} {% endblock %}

    </div>
</body>

</html>

templates/profile.html
{% extends "base.html" %} {% block content %}

<div class="container">
	<div class="row">

		<!-- sidebar of profile page -->
		<div class="col-sm-4 col-md-3">
			<div class="book-info">
				<h3 class="profile-sidebar">{{ user }}</h3>
			</div>
		</div>

		<!-- listing of all books use has borrowed -->
		<div class="col-sm-8 col-md-9">
			<h3>Borrowed books:</h3>

			{% if all_borrowings %}
				<div class="table-responsive" id="all_books">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>Name, author</th>
								<th>Borrowing date</th>
							</tr>
						</thead>
						<tbody>
							{% for borrowing in all_borrowings|dictsortreversed:"borrowing_date" %}
								<tr>
									<td>
										{{ borrowing.book.author }} –
										<a href="{% url 'books:detail' borrowing.book.id %}">
											<span class="username"><strong>{{ borrowing.book.name }}</strong></span>
										</a>
									</td>
									<td>
										{{ borrowing.borrowing_date | date:"d.m.Y" }}
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			{% endif %}
		</div>
		
	</div>
</div>

{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block content %}

	<h3>Register</h3>

	<div class="container">
		{% if registered %}
			<div class="alert alert-success" role="alert">Thank you for registering! You can now log in.</div>
		{% else %}
			<form class="form-signin" id="user_form" method="post" action="" enctype="multipart/form-data">
				{% csrf_token %}
				<label for="id_username" class="sr-only">Username:</label>
				<input id="id_username" class="form-control" name="username" type="text" placeholder="Username" required /><br>

				<label for="id_password" class="sr-only">Password:</label>
				<input id="id_password" class="form-control" name="password" type="password" placeholder="Password" required /><br>

				<button class="btn btn-lg btn-primary btn-block" type="submit" name="submit" value="Register" />Register</button>
			</form>
		{% endif %}
	</div>

{% endblock %}