books/urls.py
from django.conf.urls import url
from . import views

app_name = 'books'

urlpatterns = [
    url(r'^(?P<book_id>[0-9]+)/return/$', views.return_book, name='return'),
    url(r'^(?P<book_id>[0-9]+)/(?P<user_id>[0-9]+)/borrow/$', views.borrow, name='borrow'),
    url(r'^(?P<book_id>[0-9]+)/$', views.detail, name="detail"),
    url(r'^reviews/(?P<book_id>[0-9]+)/(?P<user_id>[0-9]+)/$', views.reviews, name='reviews'),
    url(r'^add_book/', views.add_book, name='add_book'),
    url(r'^search/', views.search, name='search'),
    url(r'^$', views.index, name='index'),
    url(r'^adminpage/', views.adminpage, name="adminpage"),
    url(r'^delete/(?P<book_id>[0-9]+)/$', views.delete_book, name='delete'),

    # todo: 'user' app for these?
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.profile, name="profile"),
    url(r'^register/', views.register, name="register"),
]

books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class Book(models.Model):
    ISBN = models.CharField(max_length=150)
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=500)
    author = models.CharField(max_length=150)
    publication_year = models.IntegerField(default=0)
    publisher = models.CharField(max_length=150)
    page_count = models.IntegerField(default=0)
    cover_URL = models.URLField(max_length=250)

    STATUS = (
        ('a', 'Available'),
        ('o', 'On loan'),
        ('n', 'Not for loan'),
    )

    status = models.CharField(
        max_length=1, choices=STATUS, blank=True, default='a')
    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    # temporarily
    borrowed = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Borrowing(models.Model):
    borrowing_date = models.DateTimeField(auto_now_add=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    returning_date = models.DateTimeField(null=True, blank=True)
    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)


class Review(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    review = models.CharField(max_length=1000)
    rating = models.IntegerField(default=1)
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE)
    reviewed_book = models.ForeignKey(Book, on_delete=models.CASCADE)

books/forms.py
from django import forms
from books.models import Book, Review
from django.contrib.auth.models import User

# book adding
class BookForm(forms.ModelForm):
    ISBN = forms.CharField(max_length=150)
    name = forms.CharField(max_length=150)
    description = forms.CharField(max_length=500)
    author = forms.CharField(max_length=150)
    publication_year = forms.IntegerField(min_value=1000, max_value=2999)
    publisher = forms.CharField(max_length=150)
    page_count = forms.IntegerField(min_value=0, max_value=9999)
    cover_URL = forms.URLField(max_length=200)

    class Meta:
        model = Book
        fields = ('ISBN', 'name', 'description', 'author', 'publication_year', 'publisher', 'page_count', 'cover_URL',)

# user registration
class UserForm(forms.ModelForm):
    username = forms.CharField(max_length=50)
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')

# review adding
class ReviewForm(forms.ModelForm):
    review = forms.CharField(max_length=1000)
    rating = forms.IntegerField(min_value=1, max_value=5)

    class Meta:
        model = Review
        fields = ('review', 'rating')

books/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from books.models import Book, Borrowing, Review
from books.forms import BookForm, UserForm, ReviewForm
from django.core.urlresolvers import reverse
from django.utils.formats import get_format
from datetime import datetime
from django.utils.dateformat import DateFormat
from django.contrib.auth.decorators import login_required, user_passes_test
from django.template import RequestContext, Context
from django.db.models import Q


def index(request):
    all_books = Book.objects.all()
    all_borrowings = Borrowing.objects.all()
    context = {'all_books': all_books, 'all_borrowings': all_borrowings}
    return render(request, 'books/index.html', context)

@user_passes_test(lambda u: u.is_superuser)
def add_book(request):
    booksurl = request.build_absolute_uri(reverse('books:index'))
    if request.method == 'POST':
        book_form = BookForm(request.POST)
        print (book_form.errors)
        if book_form.is_valid():
            book_ISBN = book_form.cleaned_data['ISBN']
            book_name = book_form.cleaned_data['name']
            book_description = book_form.cleaned_data['description']
            book_author = book_form.cleaned_data['author']
            book_publication_year = book_form.cleaned_data['publication_year']
            book_publisher = book_form.cleaned_data['publisher']
            book_page_count = book_form.cleaned_data['page_count']
            book_cover_URL = book_form.cleaned_data['cover_URL']
            new_book = Book(ISBN=book_ISBN, name=book_name, description=book_description, author=book_author,
                            publication_year=book_publication_year, publisher=book_publisher, page_count=book_page_count, cover_URL=book_cover_URL)
            new_book.save()
            return HttpResponseRedirect('/')
    else:
        book_form = BookForm()
    return render(request, 'books/add_book.html', {'booksurl': booksurl, 'book_form': book_form})

@user_passes_test(lambda u: u.is_superuser)
def adminpage(request):
    try:
        all_users = User.objects.all()
        all_borrowings = Borrowing.objects.all()
        all_reviews = Review.objects.all()
    except Book.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'admin_page.html', {'all_users': all_users, 'all_borrowings': all_borrowings, 'all_reviews': all_reviews})

# unique page for every book
def detail(request, book_id):
    try:
        book = Book.objects.get(pk=book_id)
        all_borrowings = Borrowing.objects.filter(book=book_id)
        all_reviews = Review.objects.filter(reviewed_book=book)
    except Book.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'books/detail.html', {'book': book, 'all_borrowings': all_borrowings, 'all_reviews': all_reviews})

# unique profile page for every user
@login_required
def profile(request, user_id):
    try:
        user = User.objects.get(pk=user_id)
        all_borrowings = Borrowing.objects.all()
        all_borrowings = Borrowing.objects.filter(borrower=user_id)
    except User.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'profile.html', {'user': user, 'all_borrowings': all_borrowings})

# search functionality
def search(request):
    query = request.GET.get('q')
    if query:
        results = Book.objects.filter(Q(name__icontains=query) | Q(author__icontains=query) | Q(publication_year__icontains=query) | Q(publisher__icontains=query) | Q(ISBN__icontains=query))
    else:
        results = Book.objects.all()
    all_borrowings = Borrowing.objects.all()
    context = {'results': results, 'q': query, 'all_borrowings': all_borrowings}
    return render(request, 'books/index.html', context)

@login_required
def borrow(request, book_id, user_id):
    detailurl = request.build_absolute_uri(
        reverse('books:detail', args=[book_id]))
    book = Book.objects.get(pk=book_id)
    user = User.objects.get(pk=user_id)
    book.borrowed = True
    book.borrower = user
    book.status = 'o'
    book.save()
    date = DateFormat(datetime.now()).format(get_format('DATE_FORMAT'))
    new_borrowing = Borrowing(borrowing_date=date, book=book, borrower=user)
    new_borrowing.save()
    # return render(request, 'books/detail.html', {'detailurl': detailurl, 'book': book})
    return HttpResponseRedirect('/')

@login_required
def return_book(request, book_id):
    detailurl = request.build_absolute_uri(
        reverse('books:detail', args=[book_id]))
    book = Book.objects.get(pk=book_id)
    book.borrowed = False
    book.borrower = None
    book.status = 'a'
    book.save()
    # return render(request, 'books/detail.html', {'detailurl': detailurl, 'book': book})
    return HttpResponseRedirect('/')

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print (user_form.errors)
    else:
        user_form = UserForm()
    return render(request, 'register.html', {'user_form': user_form, 'registered': registered})

# function to get every review for a specific book
def reviews(request, book_id, user_id):
    detailurl = request.build_absolute_uri(
        reverse('books:detail', args=[book_id]))
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        print (review_form.errors)
        if review_form.is_valid():
            date = DateFormat(datetime.now()).format(get_format('DATE_FORMAT'))
            review = review_form.cleaned_data['review']
            rating = review_form.cleaned_data['rating']
            book = Book.objects.get(pk=book_id)
            reviewer = request.user
            new_review = Review(
                date=date, review=review, rating=rating, reviewed_book=book, reviewer=reviewer)
            new_review.save()
            return HttpResponseRedirect(detailurl)
    else:
        review_form = ReviewForm()
    return render(request, 'books/review_book.html', {'detailurl': detailurl, 'review': review_form})

@user_passes_test(lambda u: u.is_superuser)
def delete_book(request, book_id):
    booksurl = request.build_absolute_uri(reverse('books:index'))
    detailurl = request.build_absolute_uri(reverse('books:detail', args=[book_id]))
    book = Book.objects.get(pk=book_id)
    # if OK is pressed, delete game and redirect to /games/
    if request.method == 'POST':
        book.delete()
        return HttpResponseRedirect('/')
    return render(request, 'books/delete.html', {'booksurl': booksurl, 'detailurl': detailurl, 'book': book})

books/templates/books/add_book.html
{% extends "books/base.html" %}
{% block content %}

<h3>Add book</h3>

<div class="container">

		<form class="form-signin" method="post" action="">
				{% csrf_token %}

				<label for="id_ISBN" class="sr-only">ISBN</label>
				<input class="form-control" name="ISBN" type="text" placeholder="ISBN" required /><br>

				<label for="id_book_name" class="sr-only">Book name</label>
				<input class="form-control" name="name" type="text" placeholder="Book name" required /><br>

				<label for="id_description" class="sr-only">Description</label>
				<textarea id="description-box" rows="4" class="form-control" name="description" type="text" placeholder="Description"></textarea><br>

				<label for="id_book_author" class="sr-only">Author</label>
				<input class="form-control" name="author" type="text" placeholder="Author" /><br>

				<!-- todo: add pattern -->
				<label for="id_publication_year" class="sr-only">Publication year:</label>
				<input class="form-control" name="publication_year" type="number" min="1000" max="2999" step="1" placeholder="Publication year" required /><br>

				<label for="id_publisher" class="sr-only">Publisher</label>
				<input class="form-control" name="publisher" type="text" placeholder="Publisher" /><br>

				<!-- todo: add pattern -->
				<label for="id_page_count" class="sr-only">Page count:</label>
				<input class="form-control" name="page_count" type="number" min="0" max="9999" step="1" placeholder="Page count" required /><br>

				<label for="id_cover_URL" class="sr-only">Cover URL</label>
				<input class="form-control" name="cover_URL" type="text" placeholder="Cover URL" /><br>

				<input class="btn btn-lg btn-primary btn-block" id="form-button" type="submit" value="Submit"/>

		</form>

</div>

{% endblock %}

books/templates/books/base.html
<!-- {% load staticfiles %} -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>InfoLib</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}">

</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a id="brand" href="/">InfoLib</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">

                <ul class="nav navbar-nav navbar-right">

                    <li class="navbar-text">
                        <small>Signed in as</small>
                    </li>
                    <li>
                        <a href="{% url 'books:add_book' %}">
                            Add book
                        </a>
                    </li>
                    <li>
                        <a href="">
                            Profile
                        </a>
                    </li>
                    <li>
                        <a href="">
                            Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="sisalto">

      {% block content %}
      {% endblock %}

    </div>
</body>

</html>

books/templates/books/index.html
{% extends "books/base.html" %} {% block content %}

<!-- content -->

<article id="team">
    <div class="container">
        <div class="row">
            <div class="col-sm-9">
                <h3>ALL BOOKS</h3>

                <div id="search_container">
                    <form role="search" method="get" action="/games/search/">
                        <div class="input-group search-input-group">
                            <input type="text" class="form-control" id="searchBox" class="form-control" name="q" value="" placeholder="Search">
                            <span class="input-group-addon">
                                <button type="submit">
                                    <span class="glyphicon glyphicon-search" value="search"></span>
                                </button>
                            </span>
                        </div>
                    </form>
                </div>


                {% if all_books %}

                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Publication Year</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for book in all_books %}
                                <tr>
                                    <td><a href="{% url 'books:detail' book.id %}">{{ book.name }}</a></td>
                                    <td>{{ book.author }}</td>
                                    <td>{{ book.publication_year }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                {% endif %}

            </div>
            <div class="col-sm-3">
                <h3>LATEST ACTIVITY</h3>
                <table>
                    <tbody id="recent_activity">
                        <tr>
                            <font color="#D3643B">Liisa borrowed: The Hunger Games (The Hunger Games #1)</font>
                        </tr>
                        <br>
                        <br>
                        <tr>
                            <font color="#D3643B">Joel returned: The Bible</font>
                        </tr>
                        <br>
                        <br>
                        <tr>
                            <font color="#D3643B">Admin added: Harry Potter and the Order of the Phoenix</font>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</article>

<!-- content -->


{% endblock %}